import { describe, expect, it } from "vitest";
import type { ItemCategory } from "./types";
import { registry } from "./registry";
import { getDestinations } from "../navigation/destinations";

/**
 * Exercises the registry actually bundled with the extension (generated by
 * scripts/generate-data.mjs) against the exact cases the design doc calls
 * out, plus a couple of real generator bugs caught during development
 * (see docs/data-sources.md) - most notably every Arcane and several
 * well-known items like Excalibur Prime briefly disappearing entirely
 * because of an overly aggressive "unreleased content" filter.
 */
describe("bundled registry (real generated data)", () => {
  it("resolves Protea Prime with exactly the URLs from the design spec", () => {
    const item = registry.findByWikiPath("/w/Protea/Prime");
    expect(item?.name).toBe("Protea Prime");
    expect(item?.market?.slug).toBe("protea_prime_set");
    expect(item?.overframe).toEqual({ id: 6534, slug: "protea-prime" });

    expect(registry.findByMarketSlug("protea_prime_set")).toBe(item);
    expect(registry.findByOverframeId(6534)).toBe(item);
    expect(registry.findByOverframeSlug("protea-prime")).toBe(item);
  });

  it("gives Protea Prime all three destinations from each other site", () => {
    const item = registry.findByWikiPath("/w/Protea/Prime");
    expect(item).toBeDefined();
    if (!item) return;
    expect(
      getDestinations(item, "wiki")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["market", "overframe"]);
    expect(
      getDestinations(item, "market")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["overframe", "wiki"]);
    expect(
      getDestinations(item, "overframe")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["market", "wiki"]);
  });

  it("includes every Arcane, not zero (regression: a stale 'unreleased' filter once excluded them all)", () => {
    const arcaneCount = registry.items.filter((item) => item.category === "arcane").length;
    expect(arcaneCount).toBeGreaterThan(50);
  });

  it("resolves a well-known Founders-exclusive item with only a Wiki destination", () => {
    const item = registry.findByWikiPath("/w/Excalibur/Prime");
    expect(item?.name).toBe("Excalibur Prime");
    expect(item?.market).toBeUndefined();
    expect(getDestinations(item!, "wiki")).toEqual([]);
  });

  it("gives a tradable mod Wiki and Market but never Overframe", () => {
    const item = registry.findByWikiPath("/w/Primed_Continuity");
    expect(item?.category).toBe("mod");
    expect(item?.market?.slug).toBe("primed_continuity");
    const destinations = getDestinations(item!, "wiki");
    expect(destinations.map((d) => d.site)).toEqual(["market"]);
  });

  it("gives an arcane Wiki and Market but never Overframe", () => {
    const item = registry.findByWikiPath("/w/Arcane_Energize");
    expect(item?.category).toBe("arcane");
    const destinations = getDestinations(item!, "wiki");
    expect(destinations.map((d) => d.site)).toEqual(["market"]);
  });

  it("has a large, non-trivial registry across all supported categories", () => {
    expect(registry.items.length).toBeGreaterThan(1000);
    const categories = new Set(registry.items.map((item) => item.category));
    const expectedCategories: ItemCategory[] = [
      "warframe",
      "primaryWeapon",
      "meleeWeapon",
      "mod",
      "arcane",
    ];
    for (const expected of expectedCategories) {
      expect(categories.has(expected)).toBe(true);
    }
  });
});
