import { describe, expect, it } from "vitest";
import type { ItemCategory } from "./types";
import { registry } from "./registry";
import { getDestinations } from "../navigation/destinations";

/**
 * Exercises the registry actually bundled with the extension (generated by
 * scripts/generate-data.mjs) against the exact cases the design doc calls
 * out, plus a couple of real generator bugs caught during development
 * (see docs/data-sources.md) - most notably every Arcane and several
 * well-known items like Excalibur Prime briefly disappearing entirely
 * because of an overly aggressive "unreleased content" filter.
 */
describe("bundled registry (real generated data)", () => {
  it("resolves Protea Prime with exactly the URLs from the design spec", () => {
    const item = registry.findByWikiPath("/w/Protea/Prime");
    expect(item?.name).toBe("Protea Prime");
    expect(item?.market?.slug).toBe("protea_prime_set");
    expect(item?.overframe).toEqual({ id: 6534, slug: "protea-prime" });

    expect(registry.findByMarketSlug("protea_prime_set")).toBe(item);
    expect(registry.findByOverframeId(6534)).toBe(item);
    expect(registry.findByOverframeSlug("protea-prime")).toBe(item);
  });

  it("gives Protea Prime all three destinations from each other site", () => {
    const item = registry.findByWikiPath("/w/Protea/Prime");
    expect(item).toBeDefined();
    if (!item) return;
    expect(
      getDestinations(item, "wiki")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["market", "overframe"]);
    expect(
      getDestinations(item, "market")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["overframe", "wiki"]);
    expect(
      getDestinations(item, "overframe")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["market", "wiki"]);
  });

  it("includes every Arcane, not zero (regression: a stale 'unreleased' filter once excluded them all)", () => {
    const arcaneCount = registry.items.filter((item) => item.category === "arcane").length;
    expect(arcaneCount).toBeGreaterThan(50);
  });

  it("covers the large majority of Warframes with an Overframe destination", () => {
    // Overframe has no bulk data source (see docs/data-sources.md), so
    // this is filled in by hand via data/overrides/overframe.json /
    // scripts/apply-overframe-urls.mjs - this floor documents that the
    // manual pass has actually been done, not just that the mechanism
    // exists (2 items would technically pass a >0 check).
    const warframes = registry.items.filter((item) => item.category === "warframe");
    const withOverframe = warframes.filter((item) => item.overframe);
    expect(withOverframe.length).toBeGreaterThan(warframes.length * 0.9);
  });

  it("applies a name correction (regression: WFCD's own name field disagreed with its other fields)", () => {
    // See data/overrides/corrections.json's "orion_and_sirius" entry.
    const item = registry.findByOverframeSlug("sirius-orion");
    expect(item?.name).toBe("Sirius & Orion");
    expect(item?.id).toBe("orion_and_sirius"); // id is internal-only and deliberately not rederived
  });

  it("resolves an Exalted Weapon with Wiki and Overframe but never Market", () => {
    // Exalted Blade comes bundled with Excalibur - it can never be
    // independently bought or sold, but it's exactly the kind of thing
    // people build/mod around, hence Overframe. Sourced from Misc.json's
    // "SpecialItems" productCategory - see docs/data-sources.md.
    const item = registry.findByWikiPath("/w/Exalted_Blade");
    expect(item?.name).toBe("Exalted Blade");
    expect(item?.category).toBe("exaltedWeapon");
    expect(item?.market).toBeUndefined();
    expect(getDestinations(item!, "wiki").map((d) => d.site)).toEqual(["overframe"]);
  });

  it("marks a Prime Exalted Weapon as Prime even though WFCD doesn't set isPrime for these", () => {
    const item = registry.findByWikiPath("/w/Regulators_Prime");
    expect(item?.isPrime).toBe(true);
    const nonPrime = registry.findByWikiPath("/w/Regulators");
    expect(nonPrime?.isPrime).toBe(false);
  });

  it("includes a Prime weapon's individually tradable parts, not just its set and Blueprint (regression: weapon parts were silently dropped because they don't use the \"Blueprint\" suffix Warframe parts do)", () => {
    // Acceltra Prime's Barrel/Receiver/Stock are real, tradable market
    // listings named e.g. "Acceltra Prime Barrel" - not "Acceltra Prime
    // Barrel Blueprint", unlike a Warframe's Chassis/Neuroptics/Systems
    // parts, which really are suffixed "Blueprint". buildPrimeComponents
    // used to assume every component followed the Warframe pattern,
    // which silently excluded every weapon's parts registry-wide (they
    // never resolved against warframe.market's real listings, so were
    // dropped rather than added with a wrong slug).
    const barrel = registry.findByMarketSlug("acceltra_prime_barrel");
    expect(barrel?.name).toBe("Acceltra Prime Barrel");
    expect(barrel?.category).toBe("primeComponent");
    expect(registry.findByMarketSlug("acceltra_prime_receiver")?.name).toBe(
      "Acceltra Prime Receiver",
    );
    expect(registry.findByMarketSlug("acceltra_prime_stock")?.name).toBe("Acceltra Prime Stock");
  });

  it("still resolves a Warframe's Blueprint-suffixed parts correctly (no regression from the weapon-parts fix above)", () => {
    const chassis = registry.findByMarketSlug("protea_prime_chassis_blueprint");
    expect(chassis?.name).toBe("Protea Prime Chassis Blueprint");
    expect(chassis?.category).toBe("primeComponent");
  });

  it("gives a Prime component's Overframe destination the parent item's page, not its own (it has none)", () => {
    // Real examples from the user: a component page on warframe.market
    // (e.g. "Sevagoth Prime Blueprint", "Acceltra Prime Receiver") should
    // show an Overframe button that goes to the *finished item's* build
    // page - Overframe has no page for an individual part - matching
    // generate-data.mjs's parent-wiki-path-based copying (see rules.ts
    // for why this is still "relevant," just resolved via the parent).
    const sevagothPrime = registry.findByWikiPath("/w/Sevagoth/Prime");
    const sevagothBlueprint = registry.findByMarketSlug("sevagoth_prime_blueprint");
    expect(sevagothPrime?.category).toBe("warframe");
    expect(sevagothBlueprint?.category).toBe("primeComponent");
    expect(sevagothBlueprint?.overframe).toEqual(sevagothPrime?.overframe);
    expect(sevagothBlueprint?.overframe?.slug).toBe("sevagoth-prime");
    expect(
      getDestinations(sevagothBlueprint!, "market")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["overframe", "wiki"]);

    const acceltraPrime = registry.findByWikiPath("/w/Acceltra_Prime");
    const acceltraReceiver = registry.findByMarketSlug("acceltra_prime_receiver");
    expect(acceltraReceiver?.overframe).toEqual(acceltraPrime?.overframe);
    expect(acceltraReceiver?.overframe?.slug).toBe("acceltra-prime");
  });

  it("gives every Prime component an Overframe destination whenever its parent has one (whole-registry check, not just the two examples above)", () => {
    const components = registry.items.filter((item) => item.category === "primeComponent");
    expect(components.length).toBeGreaterThan(100); // sanity: this isn't accidentally checking zero items
    for (const component of components) {
      if (!component.wiki) continue;
      const parent = registry.items.find(
        (item) => item.category !== "primeComponent" && item.wiki?.path === component.wiki?.path,
      );
      if (parent?.overframe) {
        expect(component.overframe).toEqual(parent.overframe);
      }
    }
  });

  it("never gives a well-known Founders-exclusive item a Market destination", () => {
    // Excalibur Prime is untradable (Founders-exclusive), so it should
    // never have a market slug - but it's a perfectly normal build
    // subject, so (once Overframe coverage includes it) an Overframe
    // destination is expected, not a bug. Market absence is the only
    // thing genuinely guaranteed by "Founders-exclusive" here.
    const item = registry.findByWikiPath("/w/Excalibur/Prime");
    expect(item?.name).toBe("Excalibur Prime");
    expect(item?.market).toBeUndefined();
    expect(getDestinations(item!, "wiki").map((d) => d.site)).not.toContain("market");
  });

  it("gives a tradable mod Wiki and Market but never Overframe", () => {
    const item = registry.findByWikiPath("/w/Primed_Continuity");
    expect(item?.category).toBe("mod");
    expect(item?.market?.slug).toBe("primed_continuity");
    const destinations = getDestinations(item!, "wiki");
    expect(destinations.map((d) => d.site)).toEqual(["market"]);
  });

  it("gives an arcane Wiki and Market but never Overframe", () => {
    const item = registry.findByWikiPath("/w/Arcane_Energize");
    expect(item?.category).toBe("arcane");
    const destinations = getDestinations(item!, "wiki");
    expect(destinations.map((d) => d.site)).toEqual(["market"]);
  });

  it("includes brand-new content via manual-items.json before WFCD catches up", () => {
    // Narin (Warframe), Nunchasa (Primary), and Aksondol (Secondary) from
    // a real Warframe update, added by hand (see
    // data/overrides/manual-items.json) since WFCD/warframe-items hadn't
    // published them yet at the time. No Market destination for any of
    // these - confirmed with the user these aren't tradable.
    const narin = registry.findByOverframeSlug("narin");
    expect(narin?.name).toBe("Narin");
    expect(narin?.category).toBe("warframe");
    expect(narin?.market).toBeUndefined();
    expect(getDestinations(narin!, "wiki").map((d) => d.site)).toEqual(["overframe"]);

    expect(registry.findByOverframeSlug("nunchasa")?.category).toBe("primaryWeapon");
    expect(registry.findByOverframeSlug("aksondol")?.category).toBe("secondaryWeapon");
  });

  it("gives a manually-added Prime item its full destination set, including tradable parts", () => {
    const citrinePrime = registry.findByWikiPath("/w/Citrine/Prime");
    expect(citrinePrime?.market?.slug).toBe("citrine_prime_set");
    expect(citrinePrime?.overframe?.slug).toBe("citrine-prime");
    expect(
      getDestinations(citrinePrime!, "wiki")
        .map((d) => d.site)
        .sort(),
    ).toEqual(["market", "overframe"]);

    const blueprint = registry.findByMarketSlug("citrine_prime_chassis_blueprint");
    expect(blueprint?.name).toBe("Citrine Prime Chassis Blueprint");
    expect(blueprint?.category).toBe("primeComponent");
    expect(blueprint?.overframe?.slug).toBe("citrine-prime"); // parent's, not its own
  });

  it("has a large, non-trivial registry across all supported categories", () => {
    expect(registry.items.length).toBeGreaterThan(1000);
    const categories = new Set(registry.items.map((item) => item.category));
    const expectedCategories: ItemCategory[] = [
      "warframe",
      "primaryWeapon",
      "meleeWeapon",
      "mod",
      "arcane",
    ];
    for (const expected of expectedCategories) {
      expect(categories.has(expected)).toBe(true);
    }
  });
});
